# config/routes.yaml

# Definición de rutas manejadas por controllers creado por Symfony automáticamente
# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute

# Ruta para la página de inicio
app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET
    # Puedes agregar más opciones aquí si es necesario

# Ruta para el inicio de sesión
app_login:
    path: /login
    controller: App\Controller\LoginSecurityController::login
    methods: GET
    # Puedes agregar más opciones aquí si es necesario

# Ruta para cerrar sesión
app_logout:
    path: /logout
    controller: App\Controller\LoginSecurityController::logout
    methods: GET
    # Puedes agregar más opciones aquí si es necesario

# Ruta para el registro de usuarios
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: GET
    # Puedes agregar más opciones aquí si es necesario

# Rutas para el CRUD de usuarios
app_user_index:
    path: /user
    controller: App\Controller\UserController::index
    methods: GET

app_user_new:
    path: /user/new
    controller: App\Controller\UserController::new
    methods: GET|POST

app_user_show:
    path: /user/{id}
    controller: App\Controller\UserController::show
    methods: GET

app_user_edit:
    path: /user/{id}/edit
    controller: App\Controller\UserController::edit
    methods: GET|POST

app_user_delete:
    path: /user/{id}
    controller: App\Controller\UserController::delete
    methods: POST
